### ISSUE TITLE
PHP errors

### ISSUE THREAD

**Issue by AlecRust** [mzeahmed/link-products-to-sendinblue#8]
This plugin still causes PHP errors e.g.

```
[Wed Aug 23 12:12:26.907210 2023] [proxy_fcgi:error] [pid 3850433:tid 281473491857600] [client 185.240.189.198:0] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught JsonException: Syntax error in /home/alec/web/mydomain.com/public_html/wp-content/plugins/link-products-to-sendinblue/src/Api/Api.php:78\nStack trace:\n#0 /home/alec/web/mydomain.com/public_html/wp-content/plugins/link-products-to-sendinblue/src/Api/Api.php(78): json_decode()\n#1 /home/alec/web/mydomain.com/public_html/wp-content/plugins/link-products-to-sendinblue/src/Api/Api.php(45): LPTS\\Api\\Api->make_http_request()\n#2 /home/alec/web/mydomain.com/public_html/wp-content/plugins/link-products-to-sendinblue/src/Api/Api.php(169): LPTS\\Api\\Api->get()\n#3 /home/alec/web/mydomain.com/public_html/wp-content/plugins/link-products-to-sendinblue/src/Api/Api.php(149): LPTS\\Api\\Api->get_lists()\n#4 /home/alec/web/mydomain.com/public_html/wp-content/plugins/link-products-to-sendinblue/src/Api/ApiManager.php(24): LPTS\\Api\\Api->get_all_lists()\n#5 /home/alec/web/mydomain.com/public_html/wp-content/plugins/link-products-to-sendinblue/src/Admin/Woocommerce/Cu...', referer: https://www.mydomain.com/wp-admin/admin.php?page=sensei-settings&tab=email-notification-settings
```

**Comment by AlecRust** [comment]
Looks to fail badly on new PHP versions, have to remove the plugin or can't login to WP Admin.

```
[Thu Sep 28 18:37:01.136990 2023] [proxy_fcgi:error] [pid 2751482:tid 281472650140224] [client 185.240.186.198:0] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught JsonException: Syntax error in /home/alec/web/mydomain.com/public_html/wp-content/plugins/link-products-to-sendinblue/src/Api/Api.php:78\nStack trace:\n#0 /home/alec/web/mydomain.com/public_html/wp-content/plugins/link-products-to-sendinblue/src/Api/Api.php(78): json_decode()\n#1 /home/alec/web/mydomain.com/public_html/wp-content/plugins/link-products-to-sendinblue/src/Api/Api.php(45): LPTS\\Api\\Api->make_http_request()\n#2 /home/alec/web/mydomain.com/public_html/wp-content/plugins/link-products-to-sendinblue/src/Api/Api.php(169): LPTS\\Api\\Api->get()\n#3 /home/alec/web/mydomain.com/public_html/wp-content/plugins/link-products-to-sendinblue/src/Api/Api.php(149): LPTS\\Api\\Api->get_lists()\n#4 /home/alec/web/mydomain.com/public_html/wp-content/plugins/link-products-to-sendinblue/src/Api/ApiManager.php(24): LPTS\\Api\\Api->get_all_lists()\n#5 /home/alec/web/mydomain.com/public_html/wp-content/plugins/link-products-to-sendinblue/src/Admin/Woocommerce/Cu...', referer: https://www.mydomain.com/wp-login.php
```

**Comment by AlecRust** [comment]
Since this plugin seems dead and this functionality is important to me, I built a new plugin to solve this problem:

https://wordpress.org/plugins/brevwoo/

Closing.
